language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 8
  - 9
notifications:
  flowdock: 3853ef33f6943539cbbed913648575beg
script:
  - npm test
  - npm run readme && git diff --exit-code README.md
env:
  global:
    - secure: VHyJgRz2G9C1gh+BW/ttoWOujZq+QogTdot6gdhvczB3PihZ9FFgglK0S3i4tCZFrfjBz/XMKiqF6tlQhoTQj6FD1ADSRaptel7Xv4qgcsVBffYpZS5g68gDzDG9BFOb6kes8sRJVA7Jf3OL+EhKAsvZ3e5SmHJ1SiCPdaVRSBk=
    - secure: K11WcONU2Zptx/t8GTpE2S/Gjkmt4pVEQd9tv1AAqNWdB6/FnRWd4lCemvfeU8YiDkQSh1Pm8N116u4/m0nKxNML4GLp4PPqaVK7h7MdDndjsyaHOeDlekdGFmSWa628kulrnD1/inyJjIJKf9Z5vFiVKjVo4WGWrDb2KlUr8O0=
    - secure: EzdZS4kE+Qr88RANdHGTiT9jfG5Cql2srthbkufeh3Py+tl1Zz+IIr2LUX2/l286xVAtbIUAwYHxlBmnvaZfI6gyq8fjZMCutNzf6l8XAxBxguyPIruJj7c+Fbor2hR0QScg60yOYznkTTpf0LtC4pSsTAN0vbxvPxa5i2SoWsg=
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - env: TEST_SUITE=browserstack
      node_js: '9.0'
